-- ============================================================
-- Taskastic — D1 (Cloudflare SQLite) Schema
-- Run with: npx wrangler d1 migrations apply taskastic-db
-- ============================================================

CREATE TABLE IF NOT EXISTS todos (
  id          TEXT        PRIMARY KEY,               -- UUID (generated by Worker)
  user_id     TEXT        NOT NULL,                  -- Supabase user UUID
  text        TEXT        NOT NULL,
  completed   INTEGER     NOT NULL DEFAULT 0,        -- SQLite has no BOOLEAN; 0=false, 1=true
  priority    TEXT        NOT NULL DEFAULT 'medium'
                          CHECK (priority IN ('high', 'medium', 'low')),
  status      TEXT        NOT NULL DEFAULT 'not-started'
                          CHECK (status IN ('not-started', 'active', 'completed')),
  due_date    TEXT,                                  -- ISO 8601 string or NULL
  created_at  TEXT        NOT NULL,                  -- ISO 8601 string
  updated_at  TEXT        NOT NULL                   -- ISO 8601 string
);

-- Fast lookups by user
CREATE INDEX IF NOT EXISTS idx_todos_user_id   ON todos (user_id);
-- Fast lookups for overdue queries
CREATE INDEX IF NOT EXISTS idx_todos_due_date  ON todos (due_date) WHERE due_date IS NOT NULL;
-- Ordering by creation date per user
CREATE INDEX IF NOT EXISTS idx_todos_user_created ON todos (user_id, created_at DESC);
